{{- if eq .Values.environment "DEV" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
{{- end }}
---
{{- if eq .Values.environment "DEV"}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccountName }}-crb
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  apiGroup: ""
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
{{- end }}
