apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: {{ .Values.namespace }}
  labels:
    app: consumer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      containers:
        - name: consumer
          image: "{{ .Values.registry }}{{ .Values.consumer.image }}:{{ .Values.imageTag }}"
{{- if eq $.Values.environment "DEV" }}
          tty: true
          stdin: true
{{ end }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: [{{ join "," .Values.consumer.command }}]
          ports:
            - containerPort: 8081
          readinessProbe:
            {{- toYaml .Values.consumer.readiness | nindent 12 }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment | default "DEV" }}
            - name: PYTHONWARNINGS
              value: '"ignore:Unverified HTTPS request"'
            - name: REDIS_HOST
              {{- if eq $.Values.environment "DEV" }}
              value: {{ .Values.redis.host }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: host
              {{- end }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: CELERY_BROKER_URL
              {{- if eq $.Values.environment "DEV" }}
              value: "redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}/0"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: celery_broker_url
              {{- end }}
            - name: RABBITMQ_URL
              {{- if eq $.Values.environment "DEV" }}
              value: "{{ .Values.rabbitMQ.host }},{{ .Values.rabbitMQ.port }},/"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: url
              {{- end }}
            - name: RABBITMQ_CREDENTIALS
              {{- if eq $.Values.environment "DEV" }}
              value: "{{ .Values.rabbitMQ.username }},{{ .Values.rabbitMQ.password }}"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: credentials
              {{- end }}
            - name: QUEUE_NAME
              value: {{ .Values.consumer.queueName }}
{{- if eq $.Values.environment "DEV" }}
          volumeMounts:
            - mountPath: {{ .Values.homeDir }}/consumer
              name: host-volume
            - mountPath: {{ .Values.homeDir }}/vcl-utils
              name: utils-volume
      volumes:
        - name: host-volume
          hostPath:
            path: /vcl/consumer
        - name: utils-volume
          hostPath:
            path: /vcl/vcl-utils
{{ end }}
